feat(KONFLUX-3935) Add pruning check to FBC pipeline
konflux-ci/build-definitions pull request #1744
Opened 2024-12-10 21:32 UTC by nmars

Adds a new task to the fbc-builder pipeline to check if the incoming FBC fragment would remove channels or channel entries already present in the target index.

2024-12-11 19:12 UTC, MartinBasti approved these changes
Approving CODEOWNERS change only

2024-12-18 10:28 UTC, dirgim submitted a review, later dismissed
LGTM code-wise but needs rebase and resolving the `CODEOWNERS` conflict

2025-01-10 16:20 UTC, chmeliik submitted a review, later dismissed
build-owned parts LGTM

2025-01-10 16:39 UTC, dirgim submitted a review, later dismissed
LGTM code-wise

2025-01-13 04:43 UTC, hongweiliu17 approved these changes
lgtm

2025-01-13 16:51 UTC, dirgim commented
/ok-to-test

2025-01-13 16:53 UTC, dirgim commented
/retest

2025-01-14 09:39 UTC, dirgim commented
/retest

2025-01-14 18:38 UTC, arewm requested changes
Is there specific benefit to creating an additional task for this check instead of just including it in the current `validate-fbc` task? 

By creating multiple tasks, we have to perform similar actions twice like fetching/rendering the FBC catalog. I had talked with @yashvardhannanavati about how it would be nice if the functions in the konflux-test image could reuse a common shared cache of the catalog. Separating the FBC verification checks into multiple tasks would invalidate benefits achieved with this approach.

2025-01-14 21:41 UTC, nmars commented
> Is there specific benefit to creating an additional task for this check instead of just including it in the current `validate-fbc` task?
>
> By creating multiple tasks, we have to perform similar actions twice like fetching/rendering the FBC catalog. I had talked with @yashvardhannanavati about how it would be nice if the functions in the konflux-test image could reuse a common shared cache of the catalog. Separating the FBC verification checks into multiple tasks would invalidate benefits achieved with this approach.

@arewm The benefit of having a separate check is because we want to be able to configure it for one-off exceptions. This is the proposed way to deal with the rare instances where a team needs to remove a version or channel from the target index. But they would want to ensure the other checks in `validate-fbc` would pass.

2025-01-17 14:44 UTC, dirgim commented
/ok-to-test

2025-01-17 14:47 UTC, dirgim commented
/ok-to-test

2025-01-17 14:50 UTC, nmars commented on pipelines/fbc-builder/README.md
>  |RELATED_IMAGE_ARTIFACT| The Trusted Artifact URI pointing to the artifact with the related images for the FBC fragment.| |
@arewm How does `RELATED_IMAGE_ARTIFACT` get created?

2025-01-17 15:00 UTC, nmars commented on pipelines/fbc-builder/README.md
>  |RELATED_IMAGE_ARTIFACT| The Trusted Artifact URI pointing to the artifact with the related images for the FBC fragment.| |
Latest change: the validate-fbc task was modified to create a trusted artifact from the `opm render` output. It will be pulled and used in the new check in lieu of running `opm render` again.

2025-01-20 10:10 UTC, dirgim commented
/ok-to-test

2025-01-28 08:46 UTC, dirgim commented
/ok-to-test

2025-01-29 16:05 UTC, dirgim commented
/ok-to-test

2025-01-29 22:54 UTC, yashvardhannanavati commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +    - name: TEST_OUTPUT
should IMAGES_PROCESSED also be a part of the result?

2025-01-29 22:54 UTC, yashvardhannanavati commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +    - name: OCP_VERSION
I assume this task will be run after `build-image-index` in the pipeline. May I ask from where are we getting the OCP_VERSION param? I thought you will have to extract it from the fragment inside the task. Am I missing something?

2025-01-29 22:54 UTC, yashvardhannanavati commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +        jq -s 'map(select(.schema == "olm.channel")) | reduce .[] as $obj ([]; . += [{package: $obj.package, channel: $obj.name, entries: [$obj.entries[].name]}])' "${rendered_fbc_image}" > "${fbc_ch
this could be a good addition to konflux-test image as a function. I am ok if you want to make this change in a follow-up PR

2025-01-29 22:54 UTC, yashvardhannanavati commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +        jq -s 'map(select(.schema == "olm.channel")) | reduce .[] as $obj ([]; . += [{package: $obj.package, channel: $obj.name, entries: [$obj.entries[].name]}])' "${rendered_target_index}" > "${ndx
Line 146 is duplicated here. Another reason to convert this into a function instead.

2025-01-29 23:03 UTC, arewm commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +    - name: OCP_VERSION
I had previously suggested to not redo logic that we were doing in the `validate-fbc` task (including the catalog rendering). It might be intended for this result to come from _that_ task. 

After the work that I started doing in https://github.com/konflux-ci/konflux-test/pull/356, my previous comments may have been over-aggressive as the primary motivation was to not duplicate scripts. We can achieve this same result of reducing duplication by instead leveraging the utility scripts.

2025-01-29 23:03 UTC, arewm commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +    - name: TEST_OUTPUT
(and part of the script, of course)

2025-01-30 08:39 UTC, dirgim commented
/retest

2025-01-30 14:15 UTC, nmars commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +    - name: TEST_OUTPUT
I don't think that applies in this check, which compares channel entries between the FBC image and the latest target index.

2025-01-30 14:53 UTC, dirgim commented
/ok-to-test

2025-01-30 21:38 UTC, yashvardhannanavati commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +    - name: OCP_VERSION
`validate-fbc` isn't emitting OCP_VERSION either : https://github.com/konflux-ci/build-definitions/blob/ec9936c4226e3c6e57f57a1c0e5368d4b433c925/task/validate-fbc/0.1/validate-fbc.yaml#L26 

Also, OCP_VERSION seems to be a required param. @nmars Are we confident this will work in the pipeline?

2025-01-30 21:39 UTC, yashvardhannanavati commented on task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
> +    - name: OCP_VERSION
Ah, I see you're adding it. Please ignore my previous comment

2025-01-30 23:23 UTC, yashvardhannanavati commented on task/validate-fbc/0.1/README.md
> +|OCP_VERSION|OCP version of FBC image.|
Should `RENDERED_CATALOG_DIGEST ` be added here too?

Also, could you have the changes to validate-fbc in a separate commit?

An afterthought. We should be using konflux-test helper functions to get OCP_VERSION and rendered catalog. Tekton results have a size limit and this approach wouldn't be scalable.

2025-01-30 23:23 UTC, yashvardhannanavati approved these changes
one non-blocking comment. looks good

2025-01-31 14:16 UTC, dirgim commented
/ok-to-test

2025-02-04 15:36 UTC, dirgim commented
/ok-to-test

2025-02-04 16:23 UTC, dirgim approved these changes
LGTM

2025-02-04 16:31 UTC, arewm approved these changes
no more changes requested.

2025-02-04 17:00 UTC, dirgim approved these changes
/ok-to-test

2025-02-04 17:10 UTC, dirgim commented
/ok-to-test

2025-02-04 18:48 UTC, chmeliik approved these changes

2025-02-04 18:48 UTC, MartinBasti approved these changes

2025-02-04 19:13 UTC, merged