fix(STONEINTG-373): false-positive clair report
konflux-ci/build-definitions pull request #363
Opened 2023-03-28 15:43 UTC by jsztuka

This prevents reporting false positive reports by clair in case there are 0 vulnerabilities image.

2023-03-28 18:25 UTC, dheerajodha commented
The branch is out-of-date

2023-03-29 06:52 UTC, dirgim approved these changes
LGTM

2023-03-29 06:53 UTC, dirgim commented
> The branch is out-of-date, should I click on "Update branch" on GitHub UI?

I don't think there's any need to do that in this case as there are no conflicts and the change doesn't affect the other tasks within the pipeline.

2023-03-29 07:03 UTC, dheerajodha approved these changes

2023-03-29 07:05 UTC, MartinBasti requested changes
Actually no :D this will break later on jq if `failures` is not there
`Cannot iterate over null (null)`

Can we update vulnerabilities-check.rego to always provide `failures` as and empty list

2023-03-29 07:10 UTC, dirgim commented
> Actually no :D this will break later on jq if `failures` is not there `Cannot iterate over null (null)`
> 
> Can we update vulnerabilities-check.rego to always provide `failures` as and empty list

Actually I don't think we can :/ Afaik Conftest is in charge of constructing that field.

2023-03-29 09:31 UTC, dirgim commented
Something like this e.g.:
```
critical: (.[] | .failures? // [] | map(select(.metadata.details.name=="clair_critical_vulnerabilities").metadata."vulnerabilities_number" // 0)| add // 0)
```
could work to address when there are no failures in the `clair-vulnerabilities.json`, wdyt?

2023-03-29 10:02 UTC, jsztuka commented
Still getting `Cannot iterate over null (null)` even when trying above solution.

2023-03-29 10:17 UTC, jsztuka commented
Currently getting following output:
```
STEP-CONFTEST-VULNERABILITIES

[
	{
		"filename": "/tekton/home/clair-result.json",
		"namespace": "required_checks",
		"successes": 4
	}
]
STEP-TEST-FORMAT-RESULT

{"vulnerabilities":{"critical":0,"high":0,"medium":0,"low":0}}
{"result":"SUCCESS","timestamp":"1680084268","note":"Task clair-scan completed: Refer to Tekton task result CLAIR_SCAN_RESULT for vulnerabilities scanned by Clair.","namespace":"default","successes":0,"failures":0,"warnings":0}
```

2023-03-29 11:46 UTC, MartinBasti approved these changes

2023-03-29 11:49 UTC, merged